name: Linter

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint-files:
    runs-on: ubuntu-latest
    steps:
      - name: Setup clj-kondo
        uses: DeLaGuardo/setup-clojure@master
        with:
          bb: latest

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache clj-kondo cache
        uses: actions/cache@v2
        with:
          path: .clj-kondo/.cache
          key: clj-kondo-cache-${{ hashFiles('deps.edn') }}

      - name: Lint dependencies
        run: bb lint-deps

      - name: Lint files
        run: bb lint --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
