name: tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Setup Clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.3.1040

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}

      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: gitlibs-${{ hashFiles('deps.edn') }}

      - name: Prepare dependencies
        run: clojure -P -M:test

      - name: Run Clojure tests
        run: clojure -X:test
